#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

export DISPLAY=:0

/home/uninond/uninond/uninond/scripts/launch_ff.sh &

exec fluxbox
# or if you want to keep a log:
#exec fluxbox -log "/home/uninond/.fluxbox/log"
